###
GET localhost:8080/profile/user/getProfileDetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODU1OTk1MTUsImV4cCI6MTY4NTYwMzExNSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ._1XupRjIRwOyngAjcvBZnjFmvbmWMUX9h3l1ObOLpGo